export const DETECT_NAVBAR = 'DETECT_NAVBAR';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_CARD = 'UPDATE_CARD';
export const CALCULATE_TOTALS = 'CALCULATE_TOTALS';

// User
export const ADD_USER = 'ADD_USER';

// Filters
export const SHOW_LOADING_FILTER = 'SHOW_LOADING_FILTER';
export const GET_FILTERED_ERROR = 'GET_FILTERED_ERROR';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const HANDLE_CHANGE_FILTER = 'HANDLE_CHANGE_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
